from django.urls import path
from . import views

urlpatterns = [
    path('api/register', views.register_user, name='register_user'),
    path('api/login', views.login_user, name='login_user'),
    path('api/validate-token', views.validate_token, name='validate_token'),
    path('api/logout', views.logout_user, name='logout_user'),
    path('api/verify-email/<str:token>',
         views.verify_email, name='verify_email'),
    path('api/resend-verification', views.resend_verification,
         name='resend_verification'),
    path('api/forgot-password', views.forgot_password, name='forgot_password'),
    path('api/reset-password/<str:token>',
         views.reset_password, name='reset_password'),
    path('api/update-name', views.update_user_name, name='update_user_name'),
    path('api/update-age', views.update_user_age, name='update_user_age'),
    path('api/update-gender', views.update_user_gender, name='update_user_gender'),
    path('api/update-height', views.update_user_height, name='update_user_height'),
    path('api/update-weight', views.update_user_weight, name='update_user_weight'),
    path('api/calculate-bmi', views.calculate_bmi, name='calculate_bmi'),
    path('api/update-fitness-goal', views.update_fitness_goal,
         name='update_fitness_goal'),
    path('api/update-activity-level', views.update_activity_level,
         name='update_activity_level'),
    path('api/update-reminder-mode', views.update_reminder_mode,
         name='update_reminder_mode'),
    path('api/update-diet-preference', views.update_diet_preference,
         name='update_diet_preference'),
    path('api/calculate-bmr-ideal-weight', views.calculate_bmr_and_ideal_weight,
         name='calculate_bmr_and_ideal_weight'),
    path('api/get-fitness-profile', views.get_user_fitness_profile,
         name='get_user_fitness_profile'),
    path('api/update-fitness-metrics', views.update_fitness_metrics,
         name='update_fitness_metrics'),
    path('api/get-fitness-metrics', views.get_fitness_metrics,
         name='get_fitness_metrics'),
    path('api/health-question', views.health_question, name='health_question'),
    path('api/health-qa-history', views.get_health_qa_history,
         name='get_health_qa_history'),
    path('api/update-profile', views.update_user_profile,
         name='update_user_profile'),
    path('api/update-workout-location', views.update_workout_location,
         name='update_workout_location'),
    path('api/update-equipment-preference',
         views.update_equipment_preference, name='update_equipment_preference'),
    path('api/update-workout-duration', views.update_workout_duration,
         name='update_workout_duration'),
    path('api/update-fitness-level', views.update_fitness_level,
         name='update_fitness_level'),
]
