from django.urls import path
from . import views

urlpatterns = [
    path('api/register', views.register_user, name='register_user'),
    path('api/login', views.login_user, name='login_user'),
    path('api/validate-token', views.validate_token, name='validate_token'),
    path('api/logout', views.logout_user, name='logout_user'),
    path('api/verify-email/<str:token>',
         views.verify_email, name='verify_email'),
    path('api/verify-email-code', views.verify_email_code,
         name='verify_email_code'),
    path('api/resend-verification', views.resend_verification,
         name='resend_verification'),
    path('api/forgot-password', views.forgot_password, name='forgot_password'),
    path('api/reset-password/<str:token>',
         views.reset_password, name='reset_password'),
    path('api/update-name', views.update_user_name, name='update_user_name'),
    path('api/update-age', views.update_user_age, name='update_user_age'),
    path('api/update-gender', views.update_user_gender, name='update_user_gender'),
    path('api/update-height', views.update_user_height, name='update_user_height'),
    path('api/update-weight', views.update_user_weight, name='update_user_weight'),
    path('api/calculate-bmi', views.calculate_bmi, name='calculate_bmi'),
    path('api/update-fitness-goal', views.update_fitness_goal,
         name='update_fitness_goal'),
    path('api/update-activity-level', views.update_activity_level,
         name='update_activity_level'),
    path('api/update-reminder-mode', views.update_reminder_mode,
         name='update_reminder_mode'),
    path('api/update-diet-preference', views.update_diet_preference,
         name='update_diet_preference'),
    path('api/calculate-bmr-ideal-weight', views.calculate_bmr_and_ideal_weight,
         name='calculate_bmr_and_ideal_weight'),
    path('api/get-fitness-profile', views.get_user_fitness_profile,
         name='get_user_fitness_profile'),
    path('api/update-fitness-metrics', views.update_fitness_metrics,
         name='update_fitness_metrics'),
    path('api/get-fitness-metrics', views.get_fitness_metrics,
         name='get_fitness_metrics'),
    path('api/health-question', views.health_question, name='health_question'),
    path('api/health-qa-history', views.get_health_qa_history,
         name='get_health_qa_history'),
    path('api/update-profile', views.update_user_profile,
         name='update_user_profile'),
    path('api/update-workout-location', views.update_workout_location,
         name='update_workout_location'),
    path('api/update-equipment-preference',
         views.update_equipment_preference, name='update_equipment_preference'),
    path('api/update-workout-duration', views.update_workout_duration,
         name='update_workout_duration'),
    path('api/update-fitness-level', views.update_fitness_level,
         name='update_fitness_level'),
    path('api/generate-exercise-plan', views.generate_weekly_exercise_plan,
         name='generate_weekly_exercise_plan'),
    path('api/get-exercise-plans', views.get_exercise_plans,
         name='get_exercise_plans'),
    path('api/get-exercise-plan-tips', views.get_exercise_plan_tips,
         name='get_exercise_plan_tips'),
    path('api/record-exercise-metrics', views.record_exercise_metrics,
         name='record_exercise_metrics'),
    path('api/get-exercise-metrics-history', views.get_exercise_metrics,
         name='get_exercise_metrics_history'),
    path('api/add-workout-note', views.add_workout_note,
         name='add_workout_note'),
    path('api/get-workout-notes', views.get_workout_notes,
         name='get_workout_notes'),
    path('api/update-preferences', views.update_preferences,
         name='update_preferences'),
    path('api/generate-diet-plan', views.generate_weekly_diet_plan,
         name='generate_weekly_diet_plan'),
    path('api/get-diet-plans', views.get_diet_plans,
         name='get_diet_plans'),
    path('api/update-diet-plan', views.update_diet_plan,
         name='update_diet_plan'),
    path('api/delete-diet-plan', views.delete_diet_plan,
         name='delete_diet_plan'),
    path('api/concise-health-answer', views.concise_health_answer,
         name='concise_health_answer'),
    path('api/set-food-culture', views.set_food_culture, name='set_food_culture'),
    path('api/set-user-country', views.set_user_country, name='set_user_country'),
    path('api/set-food-openness', views.set_food_openness,
         name='set_food_openness'),
    path('api/set-spice-preference', views.set_spice_preference,
         name='set_spice_preference'),
    path('api/set-allergies-restrictions',
         views.set_allergies_restrictions, name='set_allergies_restrictions'),
    path('api/get-all-users/', views.get_all_users, name='get_all_users'),
    path('api/create-group/', views.create_group, name='create_group'),
    path('api/get-groups/', views.get_groups, name='get_groups'),
    path('api/join-group/', views.join_group, name='join_group'),
    path('api/leave-group/', views.leave_group, name='leave_group'),
    path('api/user-groups/', views.get_user_groups, name='get_user_groups'),
    path('api/exercise-tips/', views.get_exercise_tips, name='get_exercise_tips'),
    path('api/send-friend-request/', views.send_friend_request,
         name='send_friend_request'),
    path('api/respond-to-friend-request/',
         views.respond_to_friend_request, name='respond_to_friend_request'),
    path('api/get-friends/', views.get_friends, name='get_friends'),
    path('api/get-friend-requests/', views.get_friend_requests,
         name='get_friend_requests'),
    path('api/log-exercise-set/', views.log_exercise_set, name='log_exercise_set'),
    path('api/get-exercise-sets/', views.get_exercise_sets,
         name='get_exercise_sets'),
    path('api/send-message/', views.send_message, name='send_message'),
    path('api/get-chat-history/', views.get_chat_history, name='get_chat_history'),

    path('api/delete-message/', views.delete_message, name='delete_message'),
    path('api/get-recent-chats/', views.get_recent_chats, name='get_recent_chats'),
    path('api/get-latest-diet-plan', views.get_latest_diet_plan,
         name='get_latest_diet_plan'),
    path('api/get-latest-exercise-plan', views.get_latest_exercise_plan,
         name='get_latest_exercise_plan'),
    path('api/food-question/', views.food_question, name='food_question'),
]
