# Generated by Django 5.2 on 2025-04-22 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_user_reset_password_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
