# Generated by Django 5.2 on 2025-04-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_user_fitness_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
