# Generated by Django 5.2 on 2025-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_user_activity_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reminder_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
