# Generated by Django 5.2 on 2025-04-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_user_reminder_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='diet_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
