# Generated by Django 5.2 on 2025-04-23 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_fitnessmetrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_qa', to='fitness.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
