# Generated by Django 5.2 on 2025-04-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_healthqa'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workout_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
