# Generated by Django 5.2 on 2025-04-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_user_workout_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='equipment_preference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
