# Generated by Django 5.2 on 2025-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_user_equipment_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='workout_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
