# Generated by Django 5.2 on 2025-04-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0014_user_workout_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fitness_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
