# Generated by Django 5.2 on 2025-04-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0017_exercisetip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_rate', models.IntegerField()),
                ('calories_burnt', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='fitness.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
