# Generated by Django 5.2 on 2025-04-24 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0018_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('calories_burnt', models.IntegerField(blank=True, null=True)),
                ('exercise_time', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_metrics', to='fitness.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
