# Generated by Django 5.2 on 2025-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0019_exercisemetrics_delete_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemetrics',
            name='exercise_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
