# Generated by Django 5.2 on 2025-04-24 16:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0020_alter_exercisemetrics_exercise_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('note_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_notes', to='fitness.user')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
