# Generated by Django 5.2 on 2025-04-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0022_dietplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
