# Generated by Django 5.2 on 2025-04-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0023_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_culture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
