# Generated by Django 5.2 on 2025-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0024_user_food_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='food_culture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
