# Generated by Django 5.2 on 2025-04-29 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0026_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_openness',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
