# Generated by Django 5.2 on 2025-04-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0027_user_food_openness'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='spice_preference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
