# Generated by Django 5.2 on 2025-04-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0028_user_spice_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
