# Generated by Django 5.2 on 2025-05-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0030_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friend_requests_sent',
            field=models.ManyToManyField(blank=True, related_name='friend_requests_received', to='fitness.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='user_friends', to='fitness.user'),
        ),
    ]
